baraja=["AS DE DIAMANTES","2 DE DIAMANTES","3 DE DIAMANTES","4 DE DIAMANTES","5 DE DIAMANTES","6 DE DIAMANTES",\
"7 DE DIAMANTES","8 DE DIAMANTES","9 DE DIAMANTES","10 DE DIAMANTES","J DE DIAMANTES","Q DE DIAMANTES","K DE DIAMANTES",\
"AS DE PICAS","2 DE PICAS","3 DE PICAS","4 DE PICAS","5 DE PICAS","6 DE PICAS","7 DE PICAS","8 DE PICAS","9 DE PICAS",\
"10 DE PICAS","J DE PICAS","Q DE PICAS","K DE PICAS","AS DE CORAZONES","2 DE CORAZONES","3 DE CORAZONES","4 DE CORAZONES",\
"5 DE CORAZONES","6 DE CORAZONES","7 DE CORAZONES","8 DE CORAZONES","9 DE CORAZONES","10 DE CORAZONES","J DE CORAZONES",\
"Q DE CORAZONES","K DE CORAZONES","AS DE TREBOL","2 DE TREBOL","3 DE TREBOL","4 DE TREBOL","5 DE TREBOL","6 DE TREBOL",\
"7 DE TREBOL","8 DE TREBOL","9 DE TREBOL","10 DE TREBOL","J DE TREBOL","Q DE TREBOL","K DE TREBOL"]